language: go

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/go-playground/overalls

script:
  - go test -v ./...
  - $GOPATH/bin/overalls -project=github.com/scompo/data-management -ignore=[.git,static,templates]
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
