#!/bin/bash
echo exporting variables...
export PRJ_NAME=github.com/scompo/data-management
export PRJ_PATH=$GOPATH/src/$PRJ_NAME
echo exported variables:
echo project name: $PRJ_NAME
echo go project path: $PRJ_PATH
echo getting project $PRJ_NAME...
go get -d $PRJ_NAME
echo changing to $PRJ_PATH...
cd $PRJ_PATH
echo git current revision:
git rev-parse master
echo downloading dependencies...
go get -t -v ./...
echo testing...
go test -v ./...
echo building...
go build ./...
echo done, thank you!
