#!/bin/bash
echo exporting variables...
export PRJ_NAME=data-management
export PRJ_FULL_PATH=github.com/scompo/$PRJ_NAME
export GO_PRJ_PATH=$GOPATH/src/$PRJ_FULL_PATH
export EXECUTABLE_PATH=$GOPATH/bin/$PRJ_NAME
echo exported variables:
echo PRJ_NAME: $PRJ_NAME
echo PRJ_FULL_PATH: $PRJ_FULL_PATH
echo GO_PRJ_PATH: $GO_PRJ_PATH
echo EXECUTABLE_PATH: $EXECUTABLE_PATH
echo removing $EXECUTABLE_PATH...
rm $EXECUTABLE_PATH
echo getting project $PRJ_FULL_PATH...
go get -d $PRJ_FULL_PATH
echo changing to $PRJ_FULL_PATH...
cd $GO_PRJ_PATH
echo git current revision:
git rev-parse master
echo downloading dependencies...
go get -t -v ./...
echo testing...
go test -v ./...
echo building...
go build -v ./...
echo created:
ls -la $EXECUTABLE_PATH
echo done, thank you!
